### ISSUE TITLE
viewer 権限で予約ができない

### ISSUE THREAD

**Issue by mmfiber** [6f-fiber-group-projects/general#6]
## 概要

viewr 権限で予約ができない
 
## 再現方法（バグのみ）

1. viewer でログイン
2. 予約

## 期待する動き

viewr 権限で予約でも予約ができる

## スクリーンショット

バグの場合は出来る限りスクリーンショットも載せてください。

## スマホ環境
 - iOS

**Comment by mmfiber** [comment]
@kiyama0 によるとPCではできて、iOS ではできなかったらしい。
iphone のデバッグ環境の構築が必要。

**Comment by kiyama0** [comment]
### バグ概要
スマホで予約するとき現時刻よりも遅い時間を入力すると、開始時刻には「現時刻よりも前の時刻は指定できません」、終了時刻には「利用開始時刻より前の日時は指定できません」と表示されます。

### スクリーンショット
![8B1C37DA-92BF-49B1-9D5E-8C2F639D2580](https://user-images.githubusercontent.com/47732235/97133809-863ef580-178e-11eb-9a57-fd96b928f826.jpeg)

###スマホ環境
iOS 13.7
IPhone 8

**Comment by mmfiber** [comment]
@mmfiber の環境では問題なく動作

**Comment by mmfiber** [comment]
ここが原因
```javascript
formatDate(d: DateInfo) {
    const hourStr = d.hour.toString().padStart(2, "0")
    const minuteStr = d.minute.toString().padStart(2, "0")
    return new Date(`${d.date}T${hourStr}:${minuteStr}:00+0900`)
  }
```

Date オブジェクトが作れていない
<img width="1440" alt="スクリーンショット 2020-10-28 16 29 19" src="https://user-images.githubusercontent.com/42595867/97405874-b4156d00-193b-11eb-858a-86425ad51d49.png">

**Comment by mmfiber** [comment]
https://qiita.com/qoAop/items/3aab78ed4e9d466cfa79
